export {
	allPrompts,
	enumToPrompts,
	GameGenre,
	animePrompts,
	fightingPrompts,
	fpsPrompts,
	genericPrompts,
	mmorpgPrompts,
	mobaPrompts,
	platformerPrompts,
	puzzlePrompts,
	racingPrompts,
	rpgPrompts,
	rhythmPrompts,
} from './image-prompts';
